Repository mitodl/salt-ops, pull requests merged in 2018-11, with the labels that each got.

#703 Updated directory structure to match code changes in the ETL repository
  salt/edx/mitx_etl.sls
Labels: DevOps

#704 Beacon to check on lmodproxy status
  pillar/beacons/http_status_lmodproxy.sls
  pillar/top.sls
Labels: DevOps, Needs Review

#705 Added nginx block to allow curling across nodes from within cluster
  pillar/nginx/micromasters_es.sls
Labels: DevOps

#706 Updated config to listen on HTTP for local connections
  pillar/nginx/micromasters_es.sls
Labels: DevOps

#707 Added dnsutils so that dig is available on instances
  salt/top.sls
  salt/utils/install_libs.sls
Labels: DevOps, enhancement

#710 Added some minor tweaks for backup/restore of residential
  salt/backups/templates/backup_mongodb.sh
  salt/backups/templates/restore_mongodb.sh
  salt/orchestrate/edx/backup.sls
Labels: DevOps

#712 Updated vault refresh schedules to be more frequent
  pillar/apps/mitx_cas.sls
  pillar/apps/odlvideo.sls
  pillar/apps/redash.sls
  pillar/apps/starcellbio.sls
  pillar/edx/init.sls
  pillar/fluentd/server.sls
  pillar/mongodb/init.sls
  pillar/rabbitmq/init.sls
  pillar/reddit.sls
Labels: DevOps
