Repository mitodl/salt-ops, pull requests merged in 2018-04, with the labels that each got.

#571 DRYing up AWS service discovery in Consul configs
  pillar/consul/apps.sls
  pillar/consul/mitx.sls
  pillar/consul/operations.sls
  pillar/consul/server.sls
Labels: DevOps

#573 add env vars for settings needed for analytics
  pillar/apps/odlvideo.sls
Labels: Waiting on Author

#576 Added edx codename as grain and conditional for static assets
  salt/edx/prod.sls
  salt/orchestrate/edx/build_ami.sls
  salt/orchestrate/edx/deploy.sls
Labels: DevOps

#577 Added Nathan to Kibana &moved mailgun alerts to their own channel
  pillar/kibana.sls
Labels: DevOps

#578 Added event triggers to backup/restore states and slack messages
  pillar/salt_master.sls
  salt/backups/backup.sls
  salt/backups/restore.sls
  salt/reactors/slack/post_event.sls
Labels: DevOps, Needs Review

#574 Build an edx sandbox environment used for testing and demos
  pillar/edx/ansible_vars.sls
  pillar/edx/residential_ansible_vars.sls
  pillar/edx/sandbox.sls
  pillar/top.sls
  salt/environment_settings.yml
  salt/top.sls
Labels: DevOps, Needs Review

#584 Changed redash_data_sources to point to MM read replica
  pillar/apps/redash_data_sources.sls
Labels: DevOps, Needs Review

#585 Added missing cloud profile for sandbox instance
  salt/orchestrate/aws/cloud_profiles/sandbox.conf
Labels: DevOps, Needs Review

#586 Removed references to shared edx pillar
  pillar/edx/ansible_vars.sls
  pillar/edx/init.sls
  pillar/edx/residential_ansible_vars.sls
  pillar/shared/edx/mitx-roles.jinja
  pillar/shared/edx/mitx.jinja
  salt/edx/prod.sls
Labels: DevOps, Needs Review

#587 Defined xqwatcher_venv_base since it was missing
  pillar/edx/xqwatcher.sls
Labels: DevOps

#589 Moved mitx-theme to residential ansible
  pillar/edx/ansible_vars.sls
  pillar/edx/residential_ansible_vars.sls
  salt/environment_settings.yml
Labels: DevOps, Needs Review

#591 Moved source repos from ansible_vars files into environment_settings
  pillar/edx/ansible_vars.sls
  pillar/edx/residential_ansible_vars.sls
  salt/environment_settings.yml
Labels: DevOps, Needs Review

#588 Added newly generated OVS cert that includes ci/rc and techtv as SANs
  pillar/nginx/odlvideo.sls
Labels: DevOps

#593 Moved memcached configuration to residential_ansible_vars
  pillar/edx/ansible_vars.sls
  pillar/edx/residential_ansible_vars.sls
  pillar/edx/sandbox.sls
Labels: DevOps

#596 Added variables for Hawthorn release
  pillar/edx/ansible_vars.sls
  pillar/edx/init.sls
  pillar/edx/mitx-production.sls
  pillar/edx/mitx-qa.sls
  pillar/edx/next_residential.sls
  pillar/edx/residential_ansible_vars.sls
  pillar/top.sls
  pillar/vault/roles/mitx.sls
  salt/environment_settings.yml
  salt/orchestrate/edx/mysql_schemas.sls
Labels: DevOps, Needs Review

#594 Make migrations if rapid-response xblock is installed
  salt/edx/migration.sls
Labels: DevOps, Needs Review
