Repository mitodl/salt-ops, pull requests merged in 2018-03, with the labels that each got.

#553 Monit checks for nginx cert expiration and latex2edx connection
  pillar/monit/latex2edx.sls
  pillar/monit/nginx_cert_expiration.sls
Labels: DevOps

#554 Monit notifications for mysql and mongodb
  pillar/monit/mongodb_connection.sls
  pillar/monit/mysql_connection.sls
Labels: DevOps, Needs Review

#556 Changed celery worker concurrency numbers
  pillar/edx/ansible_vars.sls
Labels: DevOps, Needs Review

#558 Added the scroll permission to the _all index
  pillar/elasticsearch/micromasters.sls
Labels: Waiting on Author

#559 Added the _search route to the allowed paths
  pillar/nginx/micromasters_es.sls
Labels: Waiting on Author

#560 Added elastalert check for 502 status in nginx logs
  pillar/fluentd/reddit.sls
  pillar/kibana.sls
Labels: DevOps, Waiting on Author

#561 Added a few variables to accomodate dropbox apps based on environment
  pillar/apps/odlvideo.sls
Labels: DevOps, Needs Review

#563 Moved etl pillar to analytics instance
  pillar/top.sls
Labels: DevOps

#564 Add monit pillar to edx_prod instances
  pillar/top.sls
Labels: DevOps

#568 Granting Kibana access to Matt
  pillar/kibana.sls
Labels: DevOps

#569 Added elastalert rule for mailgun discussions
  pillar/kibana.sls
Labels: DevOps, Needs Review
