Repository mitodl/salt-ops, pull requests merged in 2018-12, with the labels that each got.

#716 Added configs for storage location of video transcripts and images
  pillar/edx/ansible_vars/residential.sls
  pillar/edx/mitx-qa.sls
Labels: DevOps

#718 Overriding the DATA_DIR to fix course imports
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps

#720 Adding email config
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps

#723 Modify sensitivity of elastalert nginx 502 error
  pillar/elastalert.sls
Labels: DevOps

#725 Changed orchestrate state to use env settings
  salt/orchestrate/reddit/init.sls
Labels: DevOps

#726 Updated configs for next residential release to production
  pillar/edx/ansible_vars/next_residential.sls
  pillar/edx/ansible_vars/residential.sls
  salt/environment_settings.yml
Labels: DevOps

#727 Added delay to fluentd beacon service check
  pillar/fluentd/init.sls
Labels: DevOps, Needs Review

#722 Added beacon and reactor to restart uwsgi service on low memory
  pillar/apps/odlvideo.sls
  pillar/salt_master.sls
  salt/reactors/apps/restart_uwsgi_service_low_memory.sls
Labels: DevOps, Needs Review

#728 Removed salt-minion args since those are defined in provider
  pillar/salt_master.sls
  salt/orchestrate/aws/cloud_profiles/amps-redirect.conf
  salt/orchestrate/aws/cloud_profiles/backup_host.conf
  salt/orchestrate/aws/cloud_profiles/cassandra.conf
  salt/orchestrate/aws/cloud_profiles/consul.conf
  salt/orchestrate/aws/cloud_profiles/edx-worker.conf
  salt/orchestrate/aws/cloud_profiles/edx.conf
  salt/orchestrate/aws/cloud_profiles/edx_base.conf
  salt/orchestrate/aws/cloud_profiles/edx_forum.conf
  salt/orchestrate/aws/cloud_profiles/edx_sandbox.conf
  salt/orchestrate/aws/cloud_profiles/elasticsearch.conf
  salt/orchestrate/aws/cloud_profiles/fluentd.conf
  salt/orchestrate/aws/cloud_profiles/kibana.conf
  salt/orchestrate/aws/cloud_profiles/mitx-cas.conf
  salt/orchestrate/aws/cloud_profiles/mongodb.conf
  salt/orchestrate/aws/cloud_profiles/ocw-origin.conf
  salt/orchestrate/aws/cloud_profiles/odl-video-service.conf
  salt/orchestrate/aws/cloud_profiles/rabbitmq.conf
  salt/orchestrate/aws/cloud_profiles/redash.conf
  salt/orchestrate/aws/cloud_profiles/reddit.conf
  salt/orchestrate/aws/cloud_profiles/sandbox.conf
  salt/orchestrate/aws/cloud_profiles/scylladb.conf
  salt/orchestrate/aws/cloud_profiles/starcellbio.conf
  salt/orchestrate/aws/cloud_profiles/xqwatcher.conf
Labels: DevOps, Needs Review

#729 Updated to run via cron
  pillar/backups/mitx.sls
  pillar/backups/operations.sls
  pillar/salt_master.sls
  salt/backups/backup.sls
  salt/backups/templates/backup_consul.sh
  salt/backups/templates/backup_course_assets.sh
  salt/backups/templates/backup_elasticsearch.sh
  salt/backups/templates/backup_mongodb.sh
  salt/backups/templates/backup_mysql.sh
  salt/orchestrate/edx/backup.sls
Labels: DevOps, Needs Review

#663 Setup vault pki backends and roles to use those backends
  pillar/vault/roles/pki.sls
  salt/environment_settings.yml
  salt/vault/secret_backends.sls
Labels: DevOps, Waiting on Author
