Repository mitodl/salt-ops, pull requests merged in 2018-02, with the labels that each got.

#528 Reorganized devstack pillar files
  pillar/consul/devstack.sls
  pillar/elasticsearch/devstack.sls
  pillar/mongodb/devstack.sls
  pillar/mongodb/init.sls
  pillar/mysql/devstack.sls
  pillar/rabbitmq/devstack.sls
  pillar/top.sls
Labels: DevOps

#546 Changed query folder to reside on different volume
  pillar/edx/mitx_etl.sls
Labels: DevOps

#547 Use request_uri to pass query parameters to Elasticsearch
  pillar/nginx/micromasters_es.sls
Labels: Needs Review

#552 Added Gunicorn config to work around memory leak and promoted unicode usernames
  pillar/edx/ansible_vars.sls
  pillar/edx/mitx-qa.sls
Labels: DevOps, Needs Review

#551 Updated reddit ELB to be generic across apps
  salt/environment_settings.yml
  salt/orchestrate/aws/app_elb.sls
Labels: DevOps, Waiting on Author
