Repository mitodl/salt-ops, pull requests merged in 2018-09, with the labels that each got.

#688 Set mitx nginx logging format to match our other applications
  pillar/edx/ansible_vars/init.sls
  salt/edx/files/nginx_logging.j2
  salt/edx/prod.sls
Labels: DevOps, Needs Review

#690 Added a healtchecks check to curl when the cron job completes
  salt/edx/mitx_etl.sls
Labels: DevOps, Needs Review

#683 Added recompile assets function
  salt/orchestrate/aws/map_templates/edx.yml
  salt/orchestrate/edx/build_ami.sls
  salt/orchestrate/edx/deploy.sls
  salt/orchestrate/edx/update_edxapp_ami_sdb.sls
Labels: DevOps, Needs Review

#691 Fix etl healthcheck variable
  pillar/edx/mitx_etl.sls
  salt/edx/mitx_etl.sls
Labels: DevOps, bug

#692 Updated build_ami to use QA image for production builds
  salt/orchestrate/edx/build_ami.sls
Labels: DevOps

#693 Changed regex for date as it did not appear to be matching
  pillar/fluentd/cas.sls
Labels: DevOps, bug

#694 Added monit init to pillar top file
  pillar/top.sls
Labels: DevOps, bug

#696 Added salt reactor to notify slack when there's a cached read miss event
  pillar/salt_master.sls
  salt/reactors/vault/alert_cache_read_misses.sls
Labels: DevOps
