Repository mitodl/salt-ops, pull requests merged in 2019-06, with the labels that each got.

#873 Added configs for mooc graders to residential pillar and increased count
  pillar/edx/xqwatcher_686.sls
  pillar/edx/xqwatcher_686_residential.sls
  salt/environment_settings.yml
Labels: DevOps, Needs Review

#878 Added voucher keys and values to heroku xpro
  pillar/heroku/xpro.sls
Labels: DevOps

#883 Changed COURSE_MODE_DEFAULTS
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps

#880 xPro salt reactor autoscaling
  pillar/salt_master.sls
  salt/environment_settings.yml
  salt/orchestrate/aws/mitxpro_autoscaling.sls
  salt/reactors/mitxpro/edxapp_ec2_autoscale.sls
Labels: DevOps, Needs Review

#884 Remove hubble-salt as it's been depractaed
  pillar/salt_master.sls
Labels: DevOps

#885 Restart edx_worker if config changes
  salt/edx/run_ansible.sls
Labels: DevOps, Needs Review

#886 Added alert when account provisioning fails
  pillar/elastalert.sls
Labels: DevOps, Needs Review

#887 Added delete permission for bucket
  pillar/heroku/xpro.sls
Labels: DevOps, Needs Review

#888 Changes security groups to use id instead of name
  salt/environment_settings.yml
  salt/orchestrate/aws/mitxpro_autoscaling.sls
Labels: DevOps, Needs Review

#889 Updated versions for current QA and production for ironwood release
  salt/environment_settings.yml
Labels: DevOps

#711 WIP: remove deprecated feature flags
  pillar/edx/ansible_vars/init.sls
Labels: DevOps, Waiting on Author

#891 Added sqs engine config to salt-master
  pillar/salt_master.sls
Labels: DevOps, Needs Review

#892 Added fix for xqwatcher logging
  pillar/edx/xqwatcher.sls
  salt/edx/xqwatcher.sls
Labels: DevOps

#893 Added output of 686 grader logs to logzio
  pillar/fluentd/server.sls
  pillar/fluentd/xqwatcher.sls
  salt/orchestrate/edx/xqwatcher.sls
Labels: DevOps

#896 Added config for blocking visibility of xpro course catalog
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps

#898 Tweaks for asg to highstate new instances
  pillar/salt_master.sls
  salt/reactors/mitxpro/edxapp_ec2_autoscale.sls
  salt/reactors/mitxpro/edxapp_highstate.sls
Labels: DevOps, Needs Review

#902 Added COMMON_ENABLE_DATADOG to xpro
  pillar/edx/ansible_vars/init.sls
Labels: DevOps, Needs Review
