Repository mitodl/salt-ops, pull requests merged in 2019-12, with the labels that each got.

#1076 Updated RC feature flag value for xpro sheets feature
  .gitignore
  pillar/heroku/xpro.sls
Labels: Needs Review

#1078 Fixing fluentd prod log shipping
  pillar/fluentd/server.sls
Labels: DevOps, Needs Review

#1079 Adjust nginx max_body_size
  pillar/nginx/apps_es.sls
Labels: DevOps, Needs Review

#1081 First pass at cleaning fluentd aggreator for qa
  pillar/fluentd/server_operations_qa.sls
  pillar/top.sls
  salt/top.sls
Labels: DevOps, Needs Review

#1082 Tweaks to edx.tracking
  pillar/fluentd/mitx.sls
  pillar/fluentd/server.sls
Labels: DevOps, Needs Review

#1085 Moving established settings out of next-residential and adding pdf xblock
  pillar/edx/ansible_vars/next_residential.sls
  pillar/edx/ansible_vars/residential.sls
  pillar/top.sls
Labels: DevOps, Needs Review

#1086 Fixed tracking log parsing
  pillar/fluentd/mitx.sls
Labels: DevOps, Needs Review

#1087 Added HUBSPOT_CREATE_USER_FORM_ID to variables
  pillar/heroku/discussions.sls
Labels: DevOps, Needs Review

#1088 Added new key to right project
  pillar/heroku/discussions.sls
  pillar/heroku/xpro.sls
Labels: DevOps

#1090 Splitting schedules on the master for prod vs. qa
  pillar/master/production_schedule.sls
  pillar/master/qa_schedule.sls
  pillar/top.sls
Labels: DevOps

#1093 Added ENABLE_ORDER_RECEIPTS and set to True
  pillar/heroku/xpro.sls
Labels: DevOps, Needs Review

#1097 Changed xpro sheets task timing settings
  pillar/heroku/xpro.sls
Labels: Needs Review

#1096 Reorganizing SAML settings to make production cutover smoother
  pillar/edx/ansible_vars/next_residential.sls
  pillar/edx/ansible_vars/residential.sls
  pillar/edx/mitx-qa.sls
Labels: DevOps

#1094 Updating role definition for bootcamps to include granting of role
  pillar/vault/roles/bootcamps.sls
Labels: Data, DevOps

#1098 Adding values for SSL host override in xPRO
  pillar/heroku/xpro.sls
Labels: DevOps, Needs Review

#1102 Enabled xpro FEATURE_COUPON_SHEETS_TRACK_REQUESTER flag by default
  pillar/heroku/xpro.sls
Labels: Needs Review

#1103 Mods for fluentd qa server and pki
  pillar/fluentd/server_operations_qa.sls
  pillar/vault/roles/pki.sls
Labels: DevOps

#1108 add feature flag SHOW_UNREDEEMED_COUPON_ON_DASHBOARD
  pillar/heroku/xpro.sls
Labels: Needs Review

#1109 Added pruning of backups to backup scripts
  salt/backups/templates/backup_course_assets.sh
  salt/backups/templates/backup_mongodb.sh
  salt/backups/templates/backup_mysql.sh
Labels: DevOps

#1111 Broke out some directives into separate files
  pillar/consul/fluentd.sls
  pillar/fluentd/mitx.sls
  pillar/fluentd/server_operations_qa.sls
Labels: DevOps, Needs Review
