Repository mitodl/salt-ops, pull requests merged in 2019-07, with the labels that each got.

#900 Changed MIT xPRO labeling
  pillar/edx/ansible_vars/ecommerce.sls
Labels: DevOps, Needs Review

#906 Added xpro base URL setting for edX theme to use
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps

#905 Heroku open-discussions pillar
  pillar/heroku/discussions.sls
Labels: DevOps, Needs Review

#911 Update the list of nginx ciphers
  pillar/nginx/amps_redirect.sls
  pillar/nginx/apps_es.sls
  pillar/nginx/kibana.sls
  pillar/nginx/micromasters_es.sls
  pillar/nginx/mitx_cas.sls
  pillar/nginx/ocw_origin.sls
  pillar/nginx/odlvideo.sls
  pillar/nginx/starcellbio.sls
  salt/edx/templates/gitreload_site.j2
Labels: DevOps, Needs Review

#909 Daemonize salt-proxy
  pillar/heroku/discussions.sls
  pillar/heroku/xpro.sls
  pillar/salt_master.sls
  pillar/top.sls
Labels: DevOps, Needs Review

#914 Added xpro-theme as source_theme_repo
  salt/environment_settings.yml
Labels: DevOps, Needs Review

#915 Added edxapp vars to xpro for theme
  pillar/edx/ansible_vars/init.sls
  pillar/edx/ansible_vars/residential.sls
  pillar/edx/ansible_vars/theme.sls
  pillar/top.sls
  salt/environment_settings.yml
Labels: DevOps, Needs Review

#916 Moved XPRO_BASE_URL to production.py file
  pillar/edx/ansible_vars/xpro.sls
  salt/edx/hacks.sls
Labels: DevOps, Needs Review

#917 Added settings for controlling salt environments
  pillar/common.sls
  pillar/salt_master.sls
  salt/orchestrate/aws/map_templates/analytics_edx.yml
  salt/orchestrate/aws/map_templates/edx.yml
  salt/orchestrate/aws/map_templates/instance_map.yml
Labels: DevOps, Needs Review

#927 Minor changes to get etl working with xpro
  pillar/data/mitx_etl.sls
  salt/etl/mitx.sls
Labels: DevOps, Needs Review

#928 Resize reddit instance to t3.large
  salt/orchestrate/aws/cloud_profiles/reddit.conf
Labels: DevOps, Needs Review

#930 Add conditional to for fluentd gitreload
  pillar/fluentd/mitx.sls
Labels: DevOps, Needs Review

#929 Changes to deploy xpro analytics instance
  pillar/edx/init.sls
  pillar/top.sls
  salt/environment_settings.yml
  salt/orchestrate/aws/map_templates/analytics_edx.yml
  salt/orchestrate/edx/deploy.sls
  salt/orchestrate/edx/mitx_analytics.sls
  salt/top.sls
Labels: DevOps, Needs Review

#938 Changed link for EDXAPP_SUPPORT_SITE_LINK
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps

#936 Fix fluentD parsing of Nginx access log null value
  pillar/fluentd/cas.sls
  pillar/fluentd/ocw_origin.sls
  pillar/fluentd/odlvideo.sls
  pillar/fluentd/reddit.sls
Labels: DevOps, OCW

#939 Enable Datadog on OCW CMS & DB, production
  pillar/top.sls
  salt/top.sls
Labels: DevOps

#943 Restart edx-workers to use new creds
  pillar/edx/scheduled_jobs.sls
Labels: DevOps, Needs Review

#937 Disabled services on analytics instances
  salt/edx/run_ansible.sls
Labels: DevOps, Needs Review

#901 Added support for xpro.mit.edu subdomains on edX servers
  pillar/edx/ansible_vars/xpro.sls
  pillar/edx/mitxpro.sls
  pillar/heroku/xpro.sls
  salt/environment_settings.yml
  salt/orchestrate/aws/xpro_elb.sls
Labels: DevOps

#934 Improve file_limits sls, apply it to log cluster
  salt/top.sls
  salt/utils/file_limits.sls
Labels: DevOps

#945 Set SESSION_COOKIE_SECURE to true
  pillar/edx/ansible_vars/init.sls
Labels: DevOps, Needs Review

#951 xPro marketing link changes
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps, Needs Review, xPro

#952 Updated pillar to work with updated datadog formula
  pillar/datadog/init.sls
Labels: DevOps

#954 Check if directory exists
  salt/edx/hacks.sls
Labels: DevOps, Needs Review

#953 Added stdout and stderr log shipping for xqueue-watcher
  pillar/fluentd/server.sls
  pillar/fluentd/xqwatcher.sls
Labels: DevOps

#956 Moved JWT_AUTH to hacks.sls
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps, Needs Review, xPro

#957 Move JWT config to production.py
  pillar/edx/ansible_vars/xpro.sls
  salt/edx/hacks.sls
Labels: DevOps, Needs Review

#959 Tweaks for mitxpro autoscaling
  salt/orchestrate/aws/mitxpro_autoscaling.sls
Labels: DevOps, Needs Review

#961 Fixes to autoscaling
  salt/orchestrate/aws/mitxpro_autoscaling.sls
Labels: DevOps, Needs Review

#958 Added marketing links for edX footer
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps
