Repository mitodl/salt-ops, pull requests merged in 2019-05, with the labels that each got.

#841 Added IDA_LOGOUT_URI_LIST to xpro ansible_vars
  pillar/edx/ansible_vars/xpro.sls
  pillar/heroku/xpro.sls
Labels: DevOps, Needs Review

#844 Adding xpro RC heroku db to BI as a data source
  pillar/apps/redash_data_sources.sls
Labels: DevOps

#845 Updated states for libgit and added version to pillar
  pillar/salt_master.sls
  salt/master_utils/libgit.sls
Labels: DevOps, tech debt

#842 Updated settings and hacks to resolve SAML login
  pillar/edx/ansible_vars/next_residential.sls
  salt/edx/files/nginx_static_assets.j2
Labels: DevOps

#855 Added permissions settings for Micromasters indices on apps ES clusters
  pillar/elasticsearch/apps.sls
  pillar/elasticsearch/micromasters.sls
Labels: DevOps, Needs Review

#858 Added openedx_environment
  pillar/heroku/xpro.sls
Labels: DevOps, Needs Review

#866 Added new email address to override residential one
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps

#870 Added recaptcha keys
  pillar/heroku/xpro.sls
Labels: DevOps
