Repository mitodl/salt-ops, pull requests merged in 2019-10, with the labels that each got.

#1023 Changed pgbouncer configs to work with ci restrictions
  pillar/heroku/discussions.sls
Labels: DevOps, Needs Review

#1028 Added opsgenie_alias to reduce multiple alerts for same issue
  pillar/elastalert.sls
Labels: DevOps, Needs Review

#1029 Changes to resize residential elasticache
  salt/environment_settings.yml
Labels: DevOps, Needs Review, residential

#1032 Added memcached config options
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps, Needs Review, residential

#1033 Updated instance type and count for Redash workers
  pillar/apps/redash.sls
  salt/environment_settings.yml
  salt/orchestrate/aws/cloud_profiles/redash.conf
Labels: Data, DevOps

#1034 Added environment variables for OLL -> discussions catalog import
  pillar/heroku/discussions.sls
Labels: Waiting on Author

#1037 Added env var for xPro course api to discussions
  pillar/heroku/discussions.sls
Labels: Needs Review

#1039 Changes to add forum data to etl
  pillar/data/mitx_etl.sls
  salt/etl/mitx.sls
Labels: Data, DevOps, Needs Review

#1040 Tweaks to pki roles
  pillar/vault/roles/pki.sls
Labels: DevOps, Needs Review

#1041 Fixing list rendering in vault pki
  pillar/vault/roles/pki.sls
Labels: DevOps, Needs Review

#979 Upgraded testinfra version after fixing extension
  salt/utils/install_libs.sls
Labels: DevOps, Waiting on Author

#1042 Changed pki pillar to resolve list rendering
  pillar/vault/roles/pki.sls
Labels: DevOps, Needs Review

#1043 Updated settings for PKI roles
  pillar/vault/roles/pki.sls
Labels: DevOps
