Repository mitodl/salt-ops, pull requests merged in 2019-04, with the labels that each got.

#785 Cleaning up after fixing AMI build errors
  pillar/salt_master.sls
  salt/orchestrate/aws/cloud_profiles/edx_base.conf
  salt/orchestrate/edx/build_ami.sls
  salt/top.sls
Labels: DevOps

#787 OVS/AMPS redirect links
  pillar/nginx/amps_redirect.sls
Labels: DevOps

#790 Copy some static files to static subfolder
  salt/edx/hacks.sls
Labels: DevOps

#792 Settings and config vars to xpro
  pillar/edx/ansible_vars/xpro.sls
  pillar/heroku/xpro.sls
Labels: DevOps

#794 Fixes for xpro
  pillar/edx/ansible_vars/cloud_deployment.sls
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps

#806 Added audit keyword to course mode
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps

#807 Added env settings for xpro production environment
  salt/environment_settings.yml
Labels: DevOps, Waiting on Author

#811 Updated new mitx build runbook
  docs/runbooks/build_new_mitx_env.md
Labels: DevOps

#813 Added heroku xpro-production instance
  salt/environment_settings.yml
Labels: DevOps

#819 Changed instance type from t2 to t3
  salt/orchestrate/aws/bootcamp-ecommerce/rds.sls
  salt/orchestrate/aws/cloud_profiles/amps-redirect.conf
  salt/orchestrate/aws/cloud_profiles/cassandra.conf
  salt/orchestrate/aws/cloud_profiles/consul.conf
  salt/orchestrate/aws/cloud_profiles/edx-worker.conf
  salt/orchestrate/aws/cloud_profiles/edx_forum.conf
  salt/orchestrate/aws/cloud_profiles/fluentd.conf
  salt/orchestrate/aws/cloud_profiles/kibana.conf
  salt/orchestrate/aws/cloud_profiles/mitx-cas.conf
  salt/orchestrate/aws/cloud_profiles/mongodb.conf
  salt/orchestrate/aws/cloud_profiles/ocw-origin.conf
  salt/orchestrate/aws/cloud_profiles/odl-video-service.conf
  salt/orchestrate/aws/cloud_profiles/rabbitmq.conf
  salt/orchestrate/aws/cloud_profiles/redash.conf
  salt/orchestrate/aws/cloud_profiles/reddit.conf
  salt/orchestrate/aws/cloud_profiles/sandbox.conf
  salt/orchestrate/aws/cloud_profiles/scylladb.conf
  salt/orchestrate/aws/cloud_profiles/starcellbio.conf
  salt/orchestrate/aws/cloud_profiles/xqwatcher.conf
  salt/orchestrate/aws/micromasters/rds.sls
  salt/orchestrate/edx/services/rds.sls
  salt/orchestrate/services/elasticsearch.sls
Labels: DevOps, Needs Review

#808 Add OCW "engines" deployment
  pillar/apps/ocw-production.sls
  pillar/apps/ocw-qa.sls
  pillar/apps/ocw.sls
  pillar/top.sls
  salt/apps/ocw/engines.sls
  salt/apps/ocw/symlinks_cms.sls
  salt/apps/ocw/symlinks_origin.sls
  salt/apps/ocw/sync_repo.sls
  salt/apps/ocw/templates/engines.conf.jinja
  salt/top.sls
Labels: DevOps

#821 Updated debian ami
  salt/orchestrate/aws/cloud_profiles/backup_host.conf
  salt/orchestrate/aws/cloud_profiles/consul.conf
  salt/orchestrate/aws/cloud_profiles/elasticsearch.conf
  salt/orchestrate/aws/cloud_profiles/fluentd.conf
  salt/orchestrate/aws/cloud_profiles/kibana.conf
  salt/orchestrate/aws/cloud_profiles/mongodb.conf
  salt/orchestrate/aws/cloud_profiles/odl-video-service.conf
  salt/orchestrate/aws/cloud_profiles/rabbitmq.conf
  salt/orchestrate/aws/cloud_profiles/starcellbio.conf
Labels: DevOps

#823 Removed opts arg
  salt/backups/mount_drive.sls
  salt/orchestrate/services/cassandra.sls
  salt/orchestrate/services/mongodb.sls
  salt/orchestrate/services/scylladb.sls
Labels: DevOps, bug

#824 Added xpro-production to datadog in top files
  pillar/top.sls
  salt/top.sls
Labels: DevOps, Needs Review

#825 Added mitx to use old elasticsearch formula
  salt/top.sls
Labels: DevOps, Needs Review

#827 Updated mitx runbook and removed old state
  docs/runbooks/build_new_mitx_env.md
  salt/orchestrate/edx/services/rds.sls
Labels: DevOps, Needs Review

#828 Added variable to instance role
  docs/runbooks/build_new_mitx_env.md
  salt/orchestrate/edx/deploy.sls
Labels: DevOps, Needs Review

#836 Added help link to openedx xpro
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps, Needs Review

#835 Additions to heroku xpro and doc
  docs/runbooks/build_new_mitx_env.md
  pillar/heroku/xpro.sls
Labels: DevOps, Needs Review

#838 Override platform name & desc., MITxPro
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps

#839 Added social_auth_https_redirect to lms env production
  salt/edx/hacks.sls
Labels: DevOps, Needs Review
