Repository mitodl/salt-ops, pull requests merged in 2019-11, with the labels that each got.

#1045 Trying to pass list as string
  pillar/vault/roles/pki.sls
Labels: DevOps, Needs Review

#1046 Added ET_PRESET_IDS
  pillar/apps/odlvideo.sls
Labels: DevOps, Needs Review

#1056 Rearrange preset ids
  pillar/apps/odlvideo.sls
Labels: DevOps, Needs Review

#1000 Configuring deployment for dual masters to split envs
  .gitignore
  Pipfile
  Pipfile.lock
  bootstrap.sh
  bootstrap/README.md
  bootstrap/etc/salt/cloud.profiles.d/salt_master.conf
  bootstrap/etc/salt/cloud.providers
  bootstrap/etc/salt/master
  bootstrap/etc/salt/minion
  bootstrap/srv/pillar/top.sls
  bootstrap/srv/salt/orchestrate/configure_masters.sls
  bootstrap/srv/salt/orchestrate/deploy_masters.sls
  bootstrap/srv/salt/top.sls
  pillar/consul/init.sls
  pillar/master/config.sls
  pillar/master/extra_config.sls
  pillar/master/init.sls
  pillar/master/schedule.sls
  pillar/micromasters.sls
  pillar/mitca.sls
  pillar/top.sls
  salt/environment_settings.yml
  salt/master_utils/dns.sls
  salt/orchestrate/aws/bootcamp-ecommerce/rds.sls
  salt/orchestrate/aws/bootcamp-ecommerce/vpc.sls
  salt/orchestrate/aws/create_vpc.sls
  salt/orchestrate/aws/micromasters/dns.sls
  salt/orchestrate/aws/micromasters/rds.sls
  salt/orchestrate/aws/micromasters/vpc.sls
  salt/orchestrate/aws/operations.sls
  salt/orchestrate/aws/security_groups.sls
  salt/orchestrate/aws_env_macro.jinja
  salt/utils/install_libs.sls
Labels: DevOps, Tech Debt, enhancement

#1057 Fixed up some missing pieces for deploying QA operations environment
  bootstrap/etc/salt/master
  bootstrap/srv/salt/orchestrate/deploy_masters.sls
  pillar/master/init.sls
  pillar/vault/init.sls
  salt/orchestrate/aws/operations.sls
Labels: DevOps, Needs Review

#1060 Fix issue with old db backend roles
  pillar/vault/roles/mitx.sls
Labels: DevOps, Needs Review

#1063 Updated Consul DNS for operations services to simplify discovery
  pillar/elastic_stack/beats/init.sls
  pillar/fluentd/consul.sls
  pillar/fluentd/elasticsearch.sls
  pillar/fluentd/mitx.sls
  pillar/fluentd/mongodb.sls
  pillar/fluentd/odlvideo.sls
  pillar/fluentd/rabbitmq.sls
  pillar/fluentd/reddit.sls
  pillar/fluentd/server.sls
  pillar/fluentd/xqwatcher.sls
  pillar/master/config.sls
  salt/consul/query_template.sls
Labels: DevOps, Needs Review

#1058 Renaming and recreating security group for master SSH
  salt/orchestrate/apps/deploy.sls
  salt/orchestrate/aws/mitx.sls
  salt/orchestrate/aws/mitxpro_autoscaling.sls
  salt/orchestrate/aws/security_groups.sls
  salt/orchestrate/edx/backup.sls
  salt/orchestrate/edx/build_ami.sls
  salt/orchestrate/edx/deploy.sls
  salt/orchestrate/edx/mitx_analytics.sls
  salt/orchestrate/edx/restore.sls
  salt/orchestrate/edx/xqwatcher.sls
  salt/orchestrate/operations/services/kibana.sls
  salt/orchestrate/reddit/init.sls
  salt/orchestrate/services/cassandra.sls
  salt/orchestrate/services/consul.sls
  salt/orchestrate/services/elasticsearch.sls
  salt/orchestrate/services/mongodb.sls
  salt/orchestrate/services/rabbitmq.sls
  salt/orchestrate/services/scylladb.sls
Labels: DevOps

#1064 Added configuration for Open youtube integration
  pillar/heroku/discussions.sls
Labels: DevOps, Needs Review

#1067 Consul changes to deprecated keys
  pillar/consul/server.sls
Labels: DevOps, Needs Review

#1068 Adding configuration for xPRO integration with Google Sheets for coupon automation
  pillar/heroku/xpro.sls
Labels: DevOps

#1069 Added OPENEDX_SERVICE_WORKER_API_TOKEN
  pillar/heroku/xpro.sls
Labels: DevOps, Needs Review

#539 Change fluentd pillar for new version
  pillar/fluentd/init.sls
  pillar/fluentd/server.sls
Labels: DevOps

#1072 Fixed missing celery task logs
  pillar/apps/odlvideo.sls
Labels: DevOps, Needs Review

#1073 Fix sdb path and make it consistent with others
  salt/orchestrate/services/consul.sls
  salt/orchestrate/services/elasticsearch.sls
Labels: DevOps, Needs Review

#1074 Updated xPro/MM hosts for data etl to use SDB/consul
  pillar/heroku/discussions.sls
Labels: Needs Review
