Repository mitodl/salt-ops, pull requests merged in 2019-01, with the labels that each got.

#731 Added minion_id to datadog
  pillar/datadog/init.sls
Labels: DevOps

#730 Create secrets backends matching ones in pillar vault pki
  pillar/vault/roles/pki.sls
  salt/vault/secret_backends.sls
Labels: DevOps, Needs Review

#733 Added missing port setting for edxapp outgoing mail
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps, Needs Review

#735 Added S3 bucket definition for parsed course data from OCW
  salt/environment_settings.yml
  salt/orchestrate/aws/s3_buckets/mit_open.sls
Labels: DevOps, Waiting on Author

#737 Added hacks state to manage platform workarounds
  salt/edx/hacks.sls
  salt/top.sls
Labels: DevOps, Needs Review

#736 Added allow_bare_domain param and additional subdomains
  pillar/vault/roles/pki.sls
Labels: DevOps

#740 Added states and config for deploying mit open etl script
  pillar/data/mit_open_etl.sls
  pillar/data/mitx_etl.sls
  pillar/top.sls
  salt/edx/mitx_etl.sls
  salt/etl/init.sls
  salt/etl/mit_open.sls
  salt/etl/mitx.sls
  salt/top.sls
Labels: DevOps

#741 Deploy salt-proxy to master
  salt/heroku/proxy_config.sls
  salt/heroku/update_heroku_config.sls
  salt/top.sls
Labels: DevOps

#738 Adding environment for MITxPro
  pillar/edx/ansible_vars/ecommerce.sls
  pillar/edx/ansible_vars/init.sls
  pillar/edx/ansible_vars/residential.sls
  pillar/vault/roles/mitx.sls
  salt/environment_settings.yml
Labels: DevOps

#743 Consolidated ES settings and applied to xpro environment
  pillar/elasticsearch/mitx-qa.sls
  pillar/elasticsearch/mitx.sls
  pillar/top.sls
Labels: DevOps
