Repository mitodl/salt-ops, pull requests merged in 2019-08, with the labels that each got.

#965 Tune zope mem and cache
  salt/apps/ocw/templates/zope.conf.jinja
Labels: DevOps, OCW

#967 Remove unnecessary OCW cron jobs from engines.sls
  salt/apps/ocw/engines.sls
Labels: DevOps, OCW

#970 Fix FluentD shipping, OCW Zope and Apache access logs
  pillar/fluentd/ocw_cms.sls
Labels: DevOps, OCW

#973 Updated S3 settings to fix thumbnail uploads
  pillar/edx/ansible_vars/cloud_deployment.sls
  salt/environment_settings.yml
  salt/orchestrate/aws/s3_buckets/xpro.sls
Labels: DevOps, Needs Review

#974 Set from bulk email address in lms production
  salt/edx/hacks.sls
Labels: DevOps, Needs Review

#976 Added settings to ovs related to edx video
  pillar/apps/odlvideo.sls
Labels: DevOps, Needs Review

#963 Refactored to add edx-worker instances
  salt/environment_settings.yml
  salt/orchestrate/aws/mitxpro_autoscaling.sls
Labels: DevOps, Needs Review

#975 Updated app deployments to use release ids
  salt/orchestrate/apps/deploy.sls
  salt/orchestrate/aws/map_templates/instance_map.yml
  salt/orchestrate/edx/video/deploy.sls
  salt/orchestrate/edx/xqwatcher.sls
  salt/orchestrate/operations/services/fluentd.sls
  salt/orchestrate/operations/services/kibana.sls
  salt/orchestrate/reddit/init.sls
  salt/orchestrate/services/cassandra.sls
  salt/orchestrate/services/consul.sls
  salt/orchestrate/services/elasticsearch.sls
  salt/orchestrate/services/mongodb.sls
  salt/orchestrate/services/rabbitmq.sls
  salt/orchestrate/services/scylladb.sls
Labels: DevOps, Needs Review, enhancement

#960 Added JWT alert to xpro
  pillar/elastalert.sls
Labels: DevOps, Needs Review

#977 Updated Redash configs for 6.0 release
  pillar/apps/redash.sls
  salt/apps/redash/post_deploy.sls
Labels: Data, DevOps

#978 Added filter to avoid launching in us-east-1e
  salt/orchestrate/apps/deploy.sls
  salt/orchestrate/services/consul.sls
  salt/orchestrate/services/elasticsearch.sls
Labels: DevOps

#983 Salt envs
  pillar/common.sls
  pillar/salt_master.sls
  pillar/top.sls
  salt/orchestrate/aws/map_templates/analytics_edx.yml
  salt/orchestrate/aws/map_templates/edx.yml
  salt/orchestrate/aws/map_templates/instance_map.yml
  salt/top.sls
Labels: DevOps, enhancement

#999 Added git export functionality to xpro
  pillar/edx/ansible_vars/xpro.sls
  pillar/edx/init.sls
Labels: DevOps, Needs Review, xPro

#998 Added google analytics accounts for xpro
  pillar/edx/ansible_vars/cloud_deployment.sls
Labels: DevOps, Needs Review, xPro
