Repository mitodl/salt-ops, pull requests merged in 2020-08, with the labels that each got.

#1266 Feature flag for spam exemptions
  pillar/heroku/discussions.sls
Labels: DevOps, Waiting on Author

#1269 Update yarn and node versions to match value in package.json
  pillar/apps/odlvideo.sls
  salt/apps/odlvideo/install.sls
Labels: DevOps, Needs Review

#1270 JOBMA_LINK_EXPIRATION_DAYS
  pillar/heroku/bootcamps.sls
Labels: Waiting on Author

#1274 Fix Canvas integration settings
  pillar/edx/ansible_vars/next_residential.sls
Labels: DevOps

#1275 Added canvas config for production
  pillar/edx/ansible_vars/next_residential.sls
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps

#1276 Changed sandbox to temporarily use python2.7
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps

#1277 Added OVS nginx redirection links
  pillar/nginx/odlvideo.sls
Labels: DevOps, Needs Review
