Repository mitodl/salt-ops, pull requests merged in 2020-02, with the labels that each got.

#1155 Added OCW_ITERATOR_CHUNK_SIZE
  pillar/heroku/discussions.sls
Labels: DevOps, Needs Review

#1158 Updated sender domain for xpro production
  pillar/heroku/xpro.sls
Labels: DevOps

#1160 Additions to deploy tika in rc-apps
  salt/environment_settings.yml
  salt/orchestrate/apps/deploy.sls
  salt/orchestrate/aws/cloud_profiles/tika.conf
Labels: DevOps, Needs Review

#1161 Added nginx as proxy to tika
  pillar/nginx/tika.sls
  pillar/top.sls
  salt/environment_settings.yml
  salt/top.sls
Labels: DevOps, Needs Review

#1162 Added xPRO deferral spreadsheet heroku settings for CI/RC/prod
  pillar/heroku/xpro.sls
Labels: Needs Review

#1163 Added Tika key/values to heroku open
  pillar/heroku/discussions.sls
Labels: DevOps, Needs Review

#1164 Add keys/values to manage bootcamps config
  pillar/heroku/bootcamps.sls
  pillar/master/config.sls
  pillar/top.sls
Labels: DevOps, Needs Review

#1165 Removing master key before snapshotting AMI
  salt/orchestrate/edx/build_ami.sls
Labels: DevOps
