Repository mitodl/salt-ops, pull requests merged in 2020-03, with the labels that each got.

#1172 Added default config for data path
  pillar/elastic_stack/elasticsearch/init.sls
  pillar/elasticsearch/init.sls
Labels: Data, DevOps

#1174 add DUPLICATE_COURSES_URL config to open-discussions
  pillar/heroku/discussions.sls
Labels: Needs Review

#1173 Adding configuration for sentry log handler on master
  pillar/master/config.sls
  pillar/master/init.sls
Labels: DevOps

#1168 Change xpro support email address
  pillar/edx/ansible_vars/xpro.sls
  pillar/heroku/xpro.sls
Labels: DevOps, Needs Review

#1175 Added FEATURE_COURSE_FILE_SEARCH key
  pillar/heroku/discussions.sls
Labels: DevOps, Needs Review

#1176 Moved VOUCHER_INTERNATIONAL_* keys to prod env
  pillar/heroku/xpro.sls
Labels: DevOps, Needs Review

#1177 Added 4 memcached nodes to cluster
  salt/environment_settings.yml
Labels: DevOps, Needs Review

#1184 Change mailgun domain for OVS
  pillar/apps/odlvideo.sls
Labels: DevOps, Needs Review

#1185 Added check for starcellbio
  pillar/datadog/http-check-integration.sls
Labels: DevOps, Needs Review

#1187 Added moira app cert and key
  pillar/heroku/discussions.sls
Labels: DevOps, Needs Review

#1178 Doubled number of residential instances
  salt/environment_settings.yml
Labels: DevOps, Needs Review

#1188 Removing LORE and adding new host for Ike to CAS config
  pillar/apps/mitx_cas.sls
Labels: DevOps

#1189 Exclude netdata folder from inotify
  pillar/edx/inotify_mitx.sls
Labels: DevOps, Needs Review

#1190 Condition to skip worker service restart on base
  salt/edx/run_ansible.sls
Labels: DevOps, Needs Review

#1191 Read-only access to ES rc-apps with token
  pillar/elasticsearch/apps.sls
Labels: DevOps, Needs Review

#1192 Changed OVS url for datadog healthcheck
  pillar/datadog/http-check-integration.sls
Labels: DevOps, Needs Review

#1195 Set ENABLE_VIDEO_PERMISSIONS to True
  pillar/apps/odlvideo.sls
Labels: DevOps, Needs Review

#1196 Removed condition for moira feature
  pillar/heroku/discussions.sls
Labels: DevOps, Needs Review

#1197 Adding settings for enabling course proctoringi n residential
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps

#1198 Sync all modules before installing consul
  salt/orchestrate/edx/build_ami.sls
Labels: DevOps, Needs Review

#1199 Add FEATURE_VIDEOJS_ANNOTATIONS feature flag for RC
  pillar/apps/odlvideo.sls
Labels: DevOps
