Repository mitodl/salt-ops, pull requests merged in 2020-09, with the labels that each got.

#1278 add OCW prod domain to CORS list for Open
  pillar/heroku/discussions.sls
Labels: Needs Review

#1279 Minor changes to upgrade xpro to juniper
  pillar/edx/ansible_vars/xpro.sls
  salt/environment_settings.yml
Labels: DevOps, Needs Review

#1280 Added Canvas related feature flag
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps, Needs Review

#1281 Pointed ubcpi to edx fork
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps, Needs Review

#1282 Added max file upload size setting to bootcamps
  pillar/heroku/bootcamps.sls
Labels: Waiting on Author

#1283 Updated wildcard cert
  salt/orchestrate/aws/mitx_elb.sls
Labels: DevOps, Needs Review

#1285 Grant Brian access to logs
  pillar/nginx/kibana.sls
Labels: DevOps, Needs Review

#1284 Added config for Bootcamp integration with NovoEd for enrollments
  pillar/heroku/bootcamps.sls
Labels: Waiting on Author

#1286 Clean up JWT related settings
  pillar/edx/ansible_vars/xpro.sls
  salt/edx/hacks.sls
Labels: DevOps, Needs Review

#1287 Adding configuration handling for Dagster pipelines
  pillar/dagster/init.sls
  pillar/dagster/residential_edx.sls
  pillar/dagster/xpro_edx.sls
Labels: Data, DevOps, Needs Review

#1288 Add OPEN_DISCUSSIONS_FRONTPAGE_DIGEST_MAX_POSTS
  pillar/heroku/discussions.sls
Labels: Needs Review

#1291 Changed sandbox to use python 3.5
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps, Needs Review

#1292 Add date to compressed filename
  salt/backups/backup_tracking.sls
Labels: DevOps, Needs Review
