Repository mitodl/salt-ops, pull requests merged in 2020-05, with the labels that each got.

#1220 Added nginx to front alcali
  pillar/nginx/alcali.sls
  pillar/top.sls
  salt/top.sls
Labels: DevOps, Needs Review

#1221 Adding IAM role definition for MIT Open
  pillar/heroku/discussions.sls
  pillar/vault/roles/aws.sls
  pillar/vault/roles/macros.jinja
Labels: DevOps

#1222 Adding permissions for OCW buckets needed by MIT Open
  pillar/heroku/discussions.sls
  pillar/vault/roles/aws.sls
  salt/orchestrate/aws/s3_buckets/mit_open.sls
Labels: DevOps

#1223 Fix ALLOWED_HOSTS for bootcamps
  pillar/heroku/bootcamps.sls
Labels: Needs Review

#1225 Added cybersource keys for bootcamps
  pillar/heroku/bootcamps.sls
Labels: DevOps, Needs Review

#1227 Remove unused OCW AWS keys
  pillar/heroku/discussions.sls
Labels: Needs Review

#1228 Doc explaining used cybersource keys
  docs/runbooks/cybersource_keys.md
Labels: DevOps, Needs Review

#1226 Remove smapply and fluidreview references
  pillar/heroku/bootcamps.sls
Labels: DevOps, WIP, Waiting on Verification

#1229 Enable social auth api feature flag
  pillar/heroku/bootcamps.sls
Labels: Needs Review

#1231 Added bootcamp config vars
  pillar/heroku/bootcamps.sls
Labels: DevOps, Needs Review

#1232 Added bootcamp recaptcha keys
  pillar/heroku/bootcamps.sls
Labels: DevOps, Needs Review

#1238 Use https for bootcamp URLs
  pillar/heroku/bootcamps.sls
Labels: Waiting on Author

#1237 Remove ADMISSION_* settings that are no longer used
  pillar/heroku/bootcamps.sls
Labels: DevOps, Needs Review
