Repository mitodl/salt-ops, pull requests merged in 2020-04, with the labels that each got.

#1200 Use env_name from rc-apps to enable feature flag for videojs annotation
  pillar/apps/odlvideo.sls
Labels: Needs Review

#1202 Adding configurations for deploying Dremio server
  pillar/dremio.sls
  pillar/master/config.sls
  pillar/nginx/dremio.sls
  pillar/top.sls
  salt/environment_settings.yml
  salt/orchestrate/aws/cloud_profiles/dremio.conf
  salt/top.sls
Labels: Data, DevOps

#1203 Changes to get ProctorTrack working
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps, Needs Review

#1206 Adding feature flags for new mechanism to restrict course enrollment
  pillar/edx/ansible_vars/init.sls
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps

#1207 Setup Salt Alcali
  pillar/apps/alcali.sls
  pillar/master/config.sls
  pillar/master/extra_config.sls
  pillar/master/init.sls
  pillar/top.sls
  salt/environment_settings.yml
  salt/top.sls
Labels: DevOps, Needs Review

#1209 Change file_max_upload_size from 20 to 50
  pillar/edx/ansible_vars/cloud_deployment.sls
  pillar/edx/init.sls
Labels: DevOps, Needs Review

#1210 Only apply proctortrack settings to qa env
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps, Needs Review

#1208 Added patch of upload size to run_ansible state
  salt/edx/run_ansible.sls
Labels: DevOps

#1211 Added JWT settings for Proctor Track
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps, Needs Review

#1212 Adding state and config to create Dremio datasource in Redash
  pillar/apps/redash.sls
  salt/apps/redash/install_dremio_datasource.sls
Labels: Data, DevOps

#1213 Resize redash volume
  salt/orchestrate/aws/cloud_profiles/redash.conf
Labels: DevOps, Needs Review

#1214 Added env to app cert vault path
  pillar/apps/odlvideo.sls
Labels: DevOps, Needs Review

#1216 add GITHUB_ACCESS_TOKEN
  pillar/heroku/discussions.sls
Labels: DevOps

#1215 Add csrf cookie in residential nginx config
  salt/edx/run_ansible.sls
Labels: DevOps, Needs Review

#1217 Latests commit on ironwood to edx_proctoring
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps, Needs Review

#1218 Fix for residential csrftoken issue
  salt/edx/run_ansible.sls
Labels: DevOps, Needs Review
