Repository mitodl/salt-ops, pull requests merged in 2020-07, with the labels that each got.

#1252 Add FEATURE_CMS_HOME_PAGE=true
  pillar/heroku/bootcamps.sls
Labels: Needs Review

#1254 ProctorTrack changes
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps, Needs Review

#1255 ProctorTrack config using edxapp public values
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps, Needs Review

#1256 Fix grain deletion error
  salt/orchestrate/edx/build_ami.sls
Labels: DevOps, Needs Review

#1258 Added null to proctoring backend
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps, Needs Review

#1260 Install edx-proctoring from fork
  pillar/edx/ansible_vars/residential.sls
Labels: DevOps, Needs Review

#1262 Added Akismet configuration for Open
  pillar/heroku/discussions.sls
Labels: Needs Review

#1263 Update AKISMET_BLOG_URL to be the same for all env
  pillar/heroku/discussions.sls
Labels: Waiting on Author
