Repository mitodl/salt-ops, pull requests merged in 2020-12, with the labels that each got.

#1322 update OCW build to support new data template structure
  salt/apps/ocw/templates/webhook-publish.sh.jinja
Labels: Needs Review

#1327 CELERY_WORKER_MAX_MEMORY_PER_CHILD
  pillar/heroku/discussions.sls
Labels: DevOps, Waiting on Author

#1328 Enabled volume encryption on edx instances
  salt/orchestrate/aws/cloud_profiles/edx-worker.conf
  salt/orchestrate/aws/cloud_profiles/edx.conf
Labels: DevOps, Needs Review

#1331 Consul caddy
  pillar/caddy/consul.sls
  pillar/caddy/route53_challenge.sls
  pillar/consul/server.sls
  pillar/top.sls
  salt/environment_settings.yml
  salt/top.sls
Labels: DevOps, Needs Review

#1333 Updated mitxpro_autoscaling secgroups
  salt/orchestrate/aws/mitxpro_autoscaling.sls
Labels: DevOps, Needs Review
