Repository mitodl/salt-ops, pull requests merged in 2020-06, with the labels that each got.

#1242 Updating pillar settings for Juniper upgrade
  pillar/edx/ansible_vars/next_residential.sls
  pillar/edx/ansible_vars/residential.sls
  pillar/edx/mitx-production.sls
  pillar/edx/mitx-qa.sls
  salt/environment_settings.yml
Labels: DevOps

#1244 Added Site_Name and Hubspot config
  pillar/heroku/bootcamps.sls
Labels: DevOps, Needs Review

#1245 Updating cloud profiles to use AMD instance types
  salt/orchestrate/aws/cloud_profiles/alcali.conf
  salt/orchestrate/aws/cloud_profiles/amps-redirect.conf
  salt/orchestrate/aws/cloud_profiles/backup_host.conf
  salt/orchestrate/aws/cloud_profiles/bookkeeper.conf
  salt/orchestrate/aws/cloud_profiles/cassandra.conf
  salt/orchestrate/aws/cloud_profiles/consul.conf
  salt/orchestrate/aws/cloud_profiles/dremio.conf
  salt/orchestrate/aws/cloud_profiles/edx-worker.conf
  salt/orchestrate/aws/cloud_profiles/edx.conf
  salt/orchestrate/aws/cloud_profiles/edx_base.conf
  salt/orchestrate/aws/cloud_profiles/elasticsearch.conf
  salt/orchestrate/aws/cloud_profiles/fluentd.conf
  salt/orchestrate/aws/cloud_profiles/kibana.conf
  salt/orchestrate/aws/cloud_profiles/mitx-cas.conf
  salt/orchestrate/aws/cloud_profiles/mongodb.conf
  salt/orchestrate/aws/cloud_profiles/ocw-origin.conf
  salt/orchestrate/aws/cloud_profiles/odl-video-service.conf
  salt/orchestrate/aws/cloud_profiles/rabbitmq.conf
  salt/orchestrate/aws/cloud_profiles/redash.conf
  salt/orchestrate/aws/cloud_profiles/reddit.conf
  salt/orchestrate/aws/cloud_profiles/sandbox.conf
  salt/orchestrate/aws/cloud_profiles/scylladb.conf
  salt/orchestrate/aws/cloud_profiles/starcellbio.conf
  salt/orchestrate/aws/cloud_profiles/tika.conf
  salt/orchestrate/aws/cloud_profiles/xqwatcher.conf
  salt/orchestrate/aws/cloud_profiles/zookeeper.conf
Labels: DevOps, Needs Review

#1246 asadiqbal08/bootcamp hubspot form footer var
  pillar/heroku/bootcamps.sls
Labels: Waiting on Author

#1251 Moved jobma settings outside if conditional
  pillar/heroku/bootcamps.sls
Labels: DevOps, Needs Review
