Repository mitodl/salt-ops, pull requests merged in 2020-01, with the labels that each got.

#1115 Added OPENEDX_SERVICE_WORKER_API_TOKEN key value
  pillar/heroku/xpro.sls
Labels: DevOps, Needs Review

#1110 Pruning list of services no longer using CAS
  pillar/apps/mitx_cas.sls
Labels: DevOps, Needs Review, Tech Debt

#1112 Removing logzio configuration as it is no longer being used
  pillar/fluentd/server.sls
Labels: Data, DevOps

#1116 Added ca_chain config for fluentd
  pillar/fluentd/init.sls
Labels: DevOps, Needs Review

#1117 Added CERTIFICATE_CREATION_DELAY_IN_HOURS key/value
  pillar/heroku/xpro.sls
Labels: DevOps, Needs Review

#1118 Additional minor tweaks
  pillar/fluentd/mitx.sls
Labels: DevOps, Needs Review

#1121 Additional fluentd tweaks and yaml sdb
  pillar/fluentd/auth_log.jinja
  pillar/fluentd/cas.sls
  pillar/fluentd/consul.sls
  pillar/fluentd/elasticsearch.sls
  pillar/fluentd/init.sls
  pillar/fluentd/mitx.sls
  pillar/fluentd/mongodb.sls
  pillar/fluentd/ocw_cms.sls
  pillar/fluentd/ocw_db.sls
  pillar/fluentd/ocw_mirror.sls
  pillar/fluentd/ocw_origin.sls
  pillar/fluentd/odlvideo.sls
  pillar/fluentd/rabbitmq.sls
  pillar/fluentd/reddit.sls
  pillar/fluentd/tls_forward.jinja
  pillar/fluentd/xqwatcher.sls
  pillar/master/config.sls
  salt/sdb/keys.yaml
Labels: DevOps, Needs Review

#1124 Changed fluentd file from list to dict
  pillar/fluentd/cas.sls
  pillar/fluentd/consul.sls
  pillar/fluentd/elasticsearch.sls
  pillar/fluentd/init.sls
  pillar/fluentd/mitx.sls
  pillar/fluentd/mongodb.sls
  pillar/fluentd/ocw_cms.sls
  pillar/fluentd/ocw_db.sls
  pillar/fluentd/ocw_mirror.sls
  pillar/fluentd/ocw_origin.sls
  pillar/fluentd/odlvideo.sls
  pillar/fluentd/rabbitmq.sls
  pillar/fluentd/reddit.sls
  pillar/fluentd/server_operations_qa.sls
  pillar/fluentd/xqwatcher.sls
Labels: DevOps, Needs Review

#1125 Upgraded xpro mitxpro-openedx-extensions dependency to 0.1.1
  pillar/edx/ansible_vars/xpro.sls
Labels: Needs Review

#1122 Decreased xpro sheets monitoring frequency for non-prod envs
  pillar/heroku/xpro.sls
Labels: Needs Review

#1126 Changes to production fluentd aggregators
  pillar/fluentd/server.sls
  pillar/fluentd/server_operations_qa.sls
Labels: DevOps, Needs Review

#1131 Added tls_forward macro to accomodate env without consul
  pillar/fluentd/cas.sls
  pillar/fluentd/consul.sls
  pillar/fluentd/elasticsearch.sls
  pillar/fluentd/mitx.sls
  pillar/fluentd/mongodb.sls
  pillar/fluentd/ocw_cms.sls
  pillar/fluentd/ocw_db.sls
  pillar/fluentd/ocw_mirror.sls
  pillar/fluentd/ocw_origin.sls
  pillar/fluentd/odlvideo.sls
  pillar/fluentd/rabbitmq.sls
  pillar/fluentd/reddit.sls
  pillar/fluentd/tls_forward.jinja
  pillar/fluentd/xqwatcher.sls
Labels: DevOps, Needs Review

#1128 Changed default datadog ports on fluentd aggregators
  pillar/fluentd/server.sls
Labels: DevOps, Needs Review

#1140 Fix issue with ocw instances and fluentd
  pillar/fluentd/init.sls
Labels: DevOps, Needs Review

#1139 Alert and task to refresh saml provider metadata
  pillar/edx/init.sls
  pillar/elastalert.sls
  salt/edx/refresh_saml_provider_metadata.sls
Labels: DevOps, Needs Review

#1145 Added ELASTICSEARCH_INDEXING_CHUNK_SIZE key and set nginx value
  pillar/heroku/discussions.sls
  pillar/nginx/apps_es.sls
Labels: DevOps, Needs Review

#1146 Adding state and pillar to handle installing requirements to xqwatcher
  pillar/edx/xqwatcher_600.sls
  pillar/edx/xqwatcher_686_residential.sls
  salt/edx/xqwatcher.sls
Labels: DevOps

#1149 Replaced monit with datadog http-check
  pillar/datadog/http-check-integration.sls
  pillar/monit/init.sls
  pillar/monit/latex2edx.sls
  pillar/monit/lms_503.sls
  pillar/monit/mongodb_connection.sls
  pillar/monit/mysql_connection.sls
  pillar/monit/nginx_cert_expiration.sls
  pillar/top.sls
  salt/top.sls
Labels: DevOps, Needs Review

#1150 Reinstated logzio fluentd directives
  pillar/fluentd/server.sls
Labels: DevOps, Needs Review

#1151 Added additional endpoints and fixed tag issue
  pillar/consul/init.sls
  pillar/datadog/http-check-integration.sls
Labels: DevOps, Needs Review

#1154 Added xPRO refund spreadsheet heroku settings for CI/RC
  pillar/heroku/xpro.sls
Labels: DevOps, Needs Review

#1153 Verify tracking logs are shipping
  pillar/fluentd/server.sls
  pillar/master/config.sls
  pillar/master/production_schedule.sls
  salt/etl/verify_tracking_logs.sls
Labels: DevOps, Needs Review
