Repository mitodl/salt-ops, pull requests merged in 2020-10, with the labels that each got.

#1294 Added setting for SAML base URL in Bootcamps
  pillar/heroku/bootcamps.sls
Labels: Needs Review

#1290 xPro changes for Juniper
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps, Needs Review

#1295 Adding Caddy config to handle GitHub webhooks
  pillar/apps/ocw-next-production.sls
  pillar/apps/ocw-next-qa.sls
  pillar/caddy/ocw_build.sls
  pillar/top.sls
  salt/environment_settings.yml
  salt/top.sls
Labels: DevOps

#1296 Added NovoEd SAML login URL for Bootcamps
  pillar/heroku/bootcamps.sls
Labels: Waiting on Author

#1302 Doubled residential capacity
  salt/environment_settings.yml
Labels: DevOps

#1304 Changes to deploy juniper on xpro-qa
  salt/environment_settings.yml
Labels: DevOps, Needs Review

#1305 Fix subnet names after having them renamed
  salt/orchestrate/edx/build_ami.sls
Labels: DevOps, Needs Review

#1306 Changed xPro VPC name to match new naming
  salt/environment_settings.yml
Labels: DevOps, Needs Review
