Repository mitodl/salt-ops, pull requests merged in 2021-02, with the labels that each got.

#1358 Add GTM for OCW-Studio apps
  pillar/heroku/ocw-studio.sls
Labels: Needs Review

#1352 Initial cleanup of hacks.sls
  salt/edx/hacks.sls
Labels: Tech Debt, WIP

#1359 Removed Alcali
  pillar/apps/alcali.sls
  pillar/master/api.sls
  pillar/master/config.sls
  pillar/nginx/alcali.sls
  pillar/top.sls
  salt/environment_settings.yml
  salt/orchestrate/aws/cloud_profiles/alcali.conf
  salt/top.sls
Labels: DevOps, Needs Review, Tech Debt

#1360 Removed data http-check-integration
  pillar/beacons/http_status.sls
  pillar/datadog/http-check-integration.sls
Labels: DevOps

#1364 Change related to ovs xpro video upload issue
  pillar/apps/odlvideo.sls
Labels: DevOps, Needs Review

#969 Updated default course mode settings for xpro
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps, Waiting on Verification, xPro
