Repository mitodl/salt-ops, pull requests merged in 2021-07, with the labels that each got.

#1435 Initial mitxonline proxy commit
  pillar/heroku/mitxonline.sls
  pillar/master/config.sls
  pillar/top.sls
Labels: DevOps

#1436 ocw-studio env values for concourse pipelines
  pillar/heroku/ocw-studio.sls
Labels: Needs Review

#1437 Update production value for GITHUB_ORGANIZATION
  pillar/heroku/ocw-studio.sls
Labels: Needs Review

#1441 Run git clean -f as part of git_fetch_and_reset
  salt/apps/ocw/templates/webhook-publish.sh.jinja
Labels: Needs Review

#1440 Remove ocw-to-hugo-hash.txt
  salt/apps/ocw/templates/webhook-publish.sh.jinja
Labels: Needs Review

#1443 update OCW_ITERATOR_CHUNK_SIZE
  pillar/heroku/discussions.sls
Labels: Waiting on Author

#1444 Adding CI/RC/prod settings for NOVOED_BASE_URL in bootcamps
  pillar/heroku/bootcamps.sls
Labels: Waiting on Author
