Repository mitodl/salt-ops, pull requests merged in 2021-04, with the labels that each got.

#1392 Added Touchstone/SAML settings for OCW Studio
  pillar/heroku/ocw-studio.sls
Labels: Waiting on Author

#1395 Add extra ocw-studio SAML settings
  pillar/heroku/ocw-studio.sls
Labels: Needs Review

#1397 Fix redirect issue from google sheet
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps, Needs Review

#1396 Added DIGITAL_CREDENTIALS_SUPPORTED_RUNS configuration
  pillar/heroku/xpro.sls
Labels: Needs Review

#1393 Use ocw-to-hugo version referenced by ocw-course-hugo-theme
  pillar/apps/ocw-next-production.sls
  pillar/apps/ocw-next-qa.sls
  salt/apps/ocw/templates/webhook-publish.sh.jinja
Labels: Blocked, work in progress

#1399 Removed sentry dsn from salt-master
  pillar/master/config.sls
Labels: DevOps, Needs Review

#1401 Lilac related changes
  pillar/edx/ansible_vars/init.sls
  pillar/edx/ansible_vars/pkgs.sls
  pillar/edx/mitx-pkgs.sls
  pillar/top.sls
  salt/environment_settings.yml
  salt/orchestrate/edx/build_ami.sls
Labels: DevOps, Needs Review

#1403 Added edx-username-changer to openedx xPRO
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps, Needs Review

#1404 ES7 for mitx-qa
  pillar/elastic_stack/elasticsearch/mitx.sls
  pillar/top.sls
  salt/top.sls
Labels: DevOps, Needs Review

#1405 Changes to deploy mongodb 4.0 cluster
  pillar/mongodb/mitx-qa.sls
  pillar/top.sls
Labels: DevOps, Needs Review

#1407 Workaround for ES 7 clustering
  pillar/elastic_stack/elasticsearch/mitx.sls
Labels: DevOps

#1410 update ocw next build script to use ocw-hugo-themes
  pillar/apps/ocw-next-production.sls
  pillar/apps/ocw-next-qa.sls
  salt/apps/ocw/nextgen_build_install.sls
  salt/apps/ocw/templates/webhook-publish.sh.jinja
Labels: Blocked, Needs Review

#1411 Added forum as a service in consul
  pillar/consul/mitx-forum.sls
  pillar/edx/ansible_vars/xpro.sls
  pillar/top.sls
Labels: DevOps
