Repository mitodl/salt-ops, pull requests merged in 2021-01, with the labels that each got.

#1339 Add xpro prod refund sheet cols
  pillar/heroku/xpro.sls
Labels: Needs Review

#1337 Added refund sheet columns settings for RC
  pillar/heroku/xpro.sls
Labels: Needs Review

#1338 Basic proxy config for ocw-studio
  pillar/heroku/ocw-studio.sls
  pillar/master/config.sls
  pillar/top.sls
Labels: DevOps, Needs Review

#1342 Enabled volume encryption in cloud profiles
  salt/orchestrate/aws/cloud_profiles/backup_host.conf
  salt/orchestrate/aws/cloud_profiles/consul.conf
  salt/orchestrate/aws/cloud_profiles/dremio.conf
  salt/orchestrate/aws/cloud_profiles/elasticsearch.conf
  salt/orchestrate/aws/cloud_profiles/fluentd.conf
  salt/orchestrate/aws/cloud_profiles/mongodb.conf
  salt/orchestrate/aws/cloud_profiles/odl-video-service.conf
  salt/orchestrate/aws/cloud_profiles/rabbitmq.conf
  salt/orchestrate/aws/cloud_profiles/redash.conf
  salt/orchestrate/aws/cloud_profiles/xqwatcher.conf
Labels: DevOps, Needs Review

#1341 Additional ocw-studio config vars
  pillar/heroku/ocw-studio.sls
Labels: DevOps, Needs Review

#1350 Added NovoEd feature flag to bootcamp RC/prod
  pillar/heroku/bootcamps.sls
Labels: Needs Review

#1356 Moved XPRO_BASE_URL from hacks.sls
  pillar/edx/ansible_vars/xpro.sls
Labels: DevOps
