Repository mitodl/salt-ops, pull requests merged in 2022-02, with the labels that each got.

#1496 add env variables for theme assets pipeline
  pillar/heroku/ocw-studio.sls
Labels: Needs Review

#1497 s3 buckets for ocw-next search index
  pillar/heroku/discussions.sls
Labels: Needs Review

#1499 Email addresses for OCW Studio
  pillar/heroku/ocw-studio.sls
Labels: Needs Review

#1505 add the OCW GTM account ID to ocw-studio's configuration
  pillar/heroku/ocw-studio.sls
Labels: Needs Review

#1502 Add Cybersource settings to MITx Online
  pillar/heroku/mitxonline.sls
Labels: Waiting on Author

#1506 Initial refactor of the vector configuration management code to suppo…
  pillar/top.sls
  pillar/vector/cas.sls
  pillar/vector/init.sls
  pillar/vector/odlvideo.sls
  pillar/vector/rabbitmq.sls
  pillar/vector/reddit.sls
  pillar/vector/xqwatcher.sls
  salt/top.sls
  salt/vector/configure.sls
Labels: DevOps, Monitoring & Logging

#1501 Add VIDEO_TRANSCODE_QUEUE to ocw-studio
  pillar/heroku/ocw-studio.sls
Labels: WIP
