Repository mitodl/salt-ops, pull requests merged in 2023-05, with the labels that each got.

#1563 fix: temporarily run the course run sync taks on just fridays(MITxPRO)
  pillar/heroku/xpro.sls
Labels: Needs Review

#1562 config: add config for course run sync to be every hour (MITxOnline)
  pillar/heroku/mitxonline.sls
Labels: Needs Review

#1564 Revert "fix: temporarily run the course run sync taks on just fridays(MITxPRO)"
  pillar/heroku/xpro.sls
Labels: Needs Review, Do not merge

#1566 Adding CRON_COURSE_CERTIFICATES_HOURS to MITx Online config
  pillar/heroku/mitxonline.sls
Labels: Needs Review, product:mitx-online

#1569 Remove HUBSPOT_CREATE_USER_FORM_ID from xpro
  pillar/heroku/xpro.sls
Labels: Needs Review
