Repository mitodl/salt-ops, pull requests merged in 2023-11, with the labels that each got.

#1598 Hotfix for mitopen DATABASE_URL error
  pillar/heroku/mitopen.sls
Labels: bug

#1600 Remove reference to bootcamps-ci
  pillar/heroku/bootcamps.sls
Labels: DevOps

#1601 feat: enable blog, webinars, course topic dropdown
  pillar/heroku/xpro.sls
Labels: Needs Review
