Repository mitodl/salt-ops, pull requests merged in 2023-10, with the labels that each got.

#1588 First pass at refactoring secrets
  pillar/heroku/bootcamps.sls
Labels: DevOps, Needs Review

#1590 Update env settings for mitopen OCW resources
  pillar/heroku/mitopen.sls
Labels: Needs Review

#1592 Add Keycloak specific environment variables
  pillar/heroku/discussions.sls
Labels: Needs Review, product:infrastructure

#1597 Add MICROMASTERS_CATALOG_API_URL to mitopen env
  pillar/heroku/mitopen.sls
Labels: Needs Review
