Repository mitodl/salt-ops, pull requests merged in 2024-01, with the labels that each got.

#1606 Related to sso domain change
  pillar/heroku/mitopen.sls
Labels: DevOps

#1608 feat: add ZENDESK_DOMAIN_VERIFICATION_TAG_VALUE
  pillar/heroku/xpro.sls
Labels: Needs Review

#1610 feat: use sandbox values of ZENDESK_DOMAIN_VERIFICATION_TAG_VALUE for RC and CI
  pillar/heroku/xpro.sls
Labels: Waiting on Author

#1613 feat: add feature flag for enterprise page
  pillar/heroku/xpro.sls
Labels: Needs Review

#1612 chore: update ZENDESK_DOMAIN_VERIFICATION_TAG_VALUE & disable Enterprise feat
  pillar/heroku/xpro.sls
Labels: Needs Review
