Repository mitodl/salt-ops, pull requests merged in 2024-02, with the labels that each got.

#1617 refactor: remove zendesk tags
  pillar/heroku/xpro.sls
Labels: Waiting on Author

#1620 ocw test search params
  pillar/heroku/mitopen.sls
  pillar/heroku/ocw-studio.sls
Labels: Do not merge

#1621 config: django 4 supports CSRF values with scheme only
  pillar/heroku/xpro.sls
Labels: Needs Review
